### ISSUE TITLE
Fix 'rake db:backup' for SQLServer database

### ISSUE THREAD

**Issue by ershad** [bigbinary/boxy-cap#10]
![Alt text](https://monosnap.com/file/NeP9FJpryQ5avcKcxAbMk220gVtp24.png)

**Comment by ershad** [comment]
@neerajdotname @rkr090 Looks like we will have to make backups of database in the server it's running (windows machine), not in application server. This would need permission from database team. Is this a right time to discuss about this with database team? If yes, I will send them a mail.

![Alt text](https://monosnap.com/file/DtnuFn7yG8Kv0VNRJHOYOuo2YIijwl.png)

**Comment by neerajdotname** [comment]
I will ask Rishipal about it.
