### ISSUE TITLE
Allow capability to dynamically disable/enable database backups

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/boxy-cap#3]
Currently the scripts are tied up to a single box. If we don't need backups or database is not on same machine deployment fails.

Add an option to allow deployments for remote databases not on the rails machine.

**Comment by sahilm** [comment]
We already have the capability to connect to remote database hosts in `boxy-cap`. Testing this with an Amazon mysql RDS instance now.

**Comment by sahilm** [comment]
Backup works fine with remote Amazon mysql DB. Closing this issue.
