### ISSUE TITLE
force unicorn restart

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/boxy-cap#5]
Right now we have kill -USR2 to restart unicorn. This can cause issues when it unicorn somehow misses this USR2 signal, and the unicorn process is stuck after running for a long time.

- [ ] Investigate how to fix issue for long running unicorns that can't be killed by USR2
- [ ] Add a post deployment check to notify if unicorn doesn't restart/ timestamp of unicorn master process hasn't changed.

**Comment by sahilm** [comment]
@vipulnsward 
I'm unable to reproduce this issue. Did several hot restarts of aapc staging app. Please help.

**Comment by vipulnsward** [comment]
This is intermittent. Try restarting on a server that has not been restarted for 3-4 hours.

**Comment by sahilm** [comment]
I've tried that already. I'll search for clues.

**Comment by vipulnsward** [comment]
@sahilm did you get around this?
In the mean time please add force restart option.
